### ISSUE TITLE
Driver UI (WPF) memory leak

### ISSUE THREAD

**Issue by asdasdadsds** [OpenTabletDriver/OpenTabletDriver#972]
So I just downloaded the driver and it already uses almost 2 GB of RAM and this number keeps growing. (more than 2 gb now)
help pls 

![image](https://user-images.githubusercontent.com/82237186/114231240-385c2980-998b-11eb-9b52-8ed804b3d2a2.png)

**Comment by adryzz** [comment]
That's most probably a memory leak.
Does it happen every time or is it random?
Help > Export diagnostics
(If it doesn't help i think i'll need a memory dump to figure out what's going on)

**Comment by asdasdadsds** [comment]
[diagnostics.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6288151/diagnostics.txt)
It happens everytime. When I open the driver it uses about 200 mb but after few minutes uses more than 1 gb and every second this number grows

**Comment by adryzz** [comment]
Ok, nothing notable in the log file.
Are you able to make a memory dump and send it here when the size gets around 250MB/500MB/1GB?

![image](https://user-images.githubusercontent.com/46694241/114238550-13fd4e80-9985-11eb-8d3c-581921a0e6a7.png)

**Comment by Mrcubix** [comment]
Memory leak in Eto, not caused by OTD

**Comment by adryzz** [comment]
so it's already known to be in Eto?

**Comment by asdasdadsds** [comment]
thanks for your help, i already fixed it with older version (5.2.0)

**Comment by InfinityGhost** [comment]
> thanks for your help, i already fixed it with older version (5.2.0)

Then this issue is still valid for v0.5.2.3, this should probably stay open.

**Comment by InfinityGhost** [comment]
Likely resolved in an Eto package bump. Closing until further notice.
